name: "[internal] caller"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-ref:
    uses: dariocurr/checkout-called/.github/workflows/validate.yml@dev
    secrets: inherit

  validate-sha:
    uses: dariocurr/checkout-called/.github/workflows/validate.yml@14dd6ee11b5c4e397a3092fe723e10343fdbfdbc
    secrets: inherit
