name: "[internal] caller"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-ref:
    uses: dariocurr/checkout-called/.github/workflows/validate.yml@dev
    secrets: inherit

  validate-sha:
    uses: dariocurr/checkout-called/.github/workflows/validate.yml@fdcd1b478353dffdb9df930c83e6423e595b126c
    secrets: inherit
