name: "[internal] caller"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-ref:
    uses: dariocurr/checkout-called/.github/workflows/validate.yml@dev
    secrets: inherit

  validate-sha:
    uses: dariocurr/checkout-called/.github/workflows/validate.yml@d495b6fb26e1bca97a01047b3f123bbb2defc79e
    secrets: inherit
