name: "[TEST] called"

on:
  workflow_call:

jobs:
  called-ref:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: checkout called repo
        uses: dariocurr/checkout-called@${{ github.ref || github.sha }}
