name: "[TEST] called"

on:
  workflow_call:

jobs:
  called:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout called repo
        uses: dariocurr/checkout-called@dev
