name: "[TEST] called"

on:
  workflow_call:

jobs:
  called-ref:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: checkout called repo with ref
        uses: dariocurr/checkout-called@dev

  called-sha:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: checkout called repo with SHA
        uses: dariocurr/checkout-called@a07558a6ac1717fd1028eeda2987aaa25c7ab411
