name: "[TEST] intermidiate"

on:
  workflow_call:

jobs:
  caller-ref:
    uses: dariocurr/checkout-called/.github/workflows/called.yml@sha

  caller-sha:
    uses: dariocurr/checkout-called/.github/workflows/called.yml@461770172bfbf709f72ef3e2e96ab8d67e550ad6
