name: validate

on:
  workflow_call:

jobs:
  validate:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: checkout called repo
        uses: dariocurr/checkout-called@dev
